name: flutter_date_picker_timeline
description: A Gregorian and Jalali customizable date picker as a horizontal timeline
version: 0.3.2
homepage: https://github.com/sobimor/flutter_date_picker_timeline

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  shamsi_date: ^0.15.0
  scroll_to_index: ^2.0.0

flutter:

  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/dana.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf

 